(function() {
  if (window.MT == null) {
    window.MT = {};
  }

  window.MT.EVENTS = {
    EXTENSION_PAGE_ACTION: "EXTENSION_PAGE_ACTION",
    SCREENSHOT_REQUESTED: "SCREENSHOT_REQUESTED",
    SCREENSHOT_COMPLETED: "SCREENSHOT_COMPLETED",
    SCREENSHOT_ERROR: "SCREENSHOT_ERROR",
    REQUEST_PRE_IMPORT_DATA: "REQUEST_PRE_IMPORT_DATA",
    PROCESS_USER_PREFERENCES: "PROCESS_USER_PREFERENCE",
    IMPORT_MEDIUM_OR_WEBPAGE: "IMPORT_MEDIUM_OR_WEBPAGE",
    REQUEST_IMPORT_DATA: "REQUEST_IMPORT_DATA",
    PRE_IMPORT_DATA: "PRE_IMPORT_DATA",
    IMPORT_DATA: "IMPORT_DATA",
    RESIZE_IFRAME: "RESIZE_IFRAME",
    CONFIRM_IFRAME_LOADED: "CONFIRM_IFRAME_LOADED",
    CONFIRM_MEDIUM_LOADED: "CONFIRM_MEDIUM_LOADED",
    MEDIUM_SET_TIME: "MEDIUM_SET_TIME",
    MEDIUM_TIME_UPDATED: "MEDIUM_TIME_UPDATED",
    TEST_IMPORT_IMAGE: "TEST_IMPORT_IMAGE",
    TEST_IMPORT_WEBPAGE: "TEST_IMPORT_WEBPAGE",
    NEW_TAB_IMPORTER: "NEW_TAB_IMPORTER"
  };

}).call(this);
